### ISSUE TITLE
setting up the package on M2 Macos. 

### ISSUE THREAD

**Issue by Helia-sudo** [lcastri/fpcmci#20]
Hi, 

I could install the package on my MACos M2, but not able to use it. It seems there is issue with M1-M2 MAC. I made new environment for x86. Still it doesn't work. /anaconda3/envs/fpcmci_x86/lib/python3.8/site-packages/ruptures/utils/_utils/convert_path_matrix.cpython-38-darwin.so, 0x0002): tried: '.../anaconda3/envs/fpcmci_x86/lib/python3.8/site-packages/ruptures/utils/_utils/convert_path_matrix.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

**Comment by lcastri** [comment]
Hi,

I am sorry but I am not an expert of macOS.
I found this [link](https://stackoverflow.com/questions/70723757/arch-x86-64-and-arm64e-is-available-but-python3-is-saying-incompatible-architect) that might be useful.

Please let me know if it helps :). Otherwise, could you provide more details about the error? Specifically, which package is causing the issue?
